spring:
  datasource:
    driver-class-name: org.postgresql.Driver
    password: 1881
    url: jdbc:postgresql://localhost:5432/basics
    username: postgres
  jpa:
    hibernate:
      ddl-auto: update
    show-sql: true
  security:
    oauth2:
      client:
        registration:
          facebook:
            clientId:
            clientSecret:
            scope: email, public_profile
    user:
      name: test
      password: test
